application: bk-mrk 
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /create
  script: referrer.py

- url: /.*
  script: referrer.py

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest
